import { readFile, writeFile, mkdir, cp } from 'node:fs/promises';
import { dirname } from 'node:path';
import { marked, type Tokens } from 'marked';
import ts from 'typescript';
import { site, navigation, groups } from '../src/config.js';
import { codeBlock, escape } from '../src/highlight.js';

interface Page { title: string; description: string; status: string; path: string; group: string; file: string; body: string }
const pages: Page[] = [];
for (const item of navigation) {
  try {
    const text = await readFile(`content/docs/${item.file}`, 'utf8');
    const [, meta, body] = text.match(/^---\r?\n([\s\S]+?)\r?\n---\r?\n([\s\S]*)$/) || [];
    if (!meta) throw new Error(`Missing metadata: ${item.file}`);
    const fields = Object.fromEntries(meta.split(/\r?\n/).map(l => [l.slice(0, l.indexOf(':')), l.slice(l.indexOf(':') + 1).trim()]));
    pages.push({ ...item, title: fields.title, description: fields.description, status: fields.status || 'Implemented', body });
  } catch (error) { if (process.env.INITIAL_PREVIEW !== '1') throw error; }
}
const slug = (s: string) => s.toLowerCase().replace(/<[^>]*>/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
function render(body: string) {
  const headings: { title: string; id: string; level: number }[] = [];
  const ids = new Map<string, number>();
  const renderer = new marked.Renderer();
  renderer.code = ({ text, lang }: Tokens.Code) => codeBlock(text, lang || 'text');
  renderer.heading = function ({ tokens, depth }: Tokens.Heading) {
    const title = this.parser.parseInline(tokens); const base = slug(title); const count = ids.get(base) || 0; ids.set(base, count + 1); const id = base + (count ? `-${count}` : '');
    headings.push({ title: title.replace(/<[^>]*>/g, ''), id, level: depth });
    return `<h${depth} id="${id}"><a class="heading-anchor" href="#${id}" aria-label="Link to ${escape(title.replace(/<[^>]*>/g, ''))}">${title}<span aria-hidden="true">#</span></a></h${depth}>`;
  };
  const html = marked.parse(body, { renderer, async: false }).replace(/<blockquote>\s*<p>\[!(Note|Tip|Warning|Important|Experimental)\]\s*([\s\S]*?)<\/p>\s*<\/blockquote>/g, (_, kind: string, text: string) => `<aside class="callout ${kind.toLowerCase()}"><strong>${kind}</strong><p>${text}</p></aside>`);
  return { html, headings };
}
const logo = `<img src="/assets/skuld.svg" width="30" height="30" alt=""><span>skuld<span class="brand-dot">.</span></span>`;
function header(path: string) { return `<header class="header"><a class="brand" href="/" aria-label="Skuld home">${logo}</a><span class="header-divider"></span><nav aria-label="Main"><a ${path.startsWith('/docs/') || path === '/docs/' ? 'aria-current="page"' : ''} href="/docs/">Docs</a><a ${path === '/examples/' ? 'aria-current="page"' : ''} href="/examples/">Examples</a><a ${path === '/playground/' ? 'aria-current="page"' : ''} href="/playground/">Playground</a><a href="/docs/standard-library/overview/">Standard library</a></nav><button class="search-trigger" data-search><span aria-hidden="true">⌕</span> <span>Search documentation</span><kbd>Ctrl K</kbd></button><a class="github" href="${site.github}">GitHub <span aria-hidden="true">↗</span></a><label class="sr-only" for="theme">Theme</label><select id="theme" aria-label="Color theme"><option value="system">System</option><option value="dark">Dark</option><option value="light">Light</option></select><button class="mobile-toggle" aria-label="Open navigation" aria-expanded="false" aria-controls="mobile-navigation">☰</button></header>`; }
function side(path: string) { return `<a class="sidebar-home" href="/docs/">Documentation <span>↗</span></a><label class="version">VERSION<select aria-label="Documentation version"><option>v${site.version} · current</option></select></label>${groups.map((g, i) => `<details class="nav-group" data-group="${i}" open><summary>${g.title}</summary><div>${navigation.filter(n => n.group === g.title).map(n => `<a href="${n.path}" ${path === n.path ? 'aria-current="page"' : ''}>${escape(pages.find(p => p.path === n.path)?.title || n.slug.replaceAll('-', ' '))}${pages.find(p => p.path === n.path)?.status === 'Planned' ? '<span class="nav-planned">Planned</span>' : ''}</a>`).join('')}</div></details>`).join('')}<a class="sidebar-bottom" href="/changelog/">Changelog <span>↗</span></a>`; }
function shell(title: string, description: string, path: string, content: string, toc = '', isDoc = false) {
  return `<!doctype html><html lang="en" data-theme="dark"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)} | Skuld Documentation</title><meta name="description" content="${escape(description)}"><meta property="og:title" content="${escape(title)} | Skuld"><meta property="og:description" content="${escape(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${site.origin}${path}"><link rel="canonical" href="${site.origin}${path}"><link rel="icon" href="/assets/skuld.svg" type="image/svg+xml"><script>try{const t=localStorage.getItem('skuld-theme')||'system';document.documentElement.dataset.theme=t==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):t}catch{}</script><link rel="stylesheet" href="/assets/site.css"><script type="module" src="/assets/client.js"></script></head><body><a class="skip-link" href="#main">Skip to content</a>${header(path)}<dialog id="mobile-navigation" class="mobile-nav" aria-label="Navigation"><button class="close-dialog" aria-label="Close navigation">Close ×</button><nav aria-label="Mobile main"><a href="/docs/">Docs</a><a href="/examples/">Examples</a><a href="/playground/">Playground</a><a href="${site.github}">GitHub ↗</a></nav><nav aria-label="Mobile documentation">${side(path)}</nav></dialog>${isDoc ? `<div class="docs-layout"><aside class="sidebar" aria-label="Documentation navigation"><nav aria-label="Documentation">${side(path)}</nav></aside><main id="main" class="article" tabindex="-1">${content}</main><aside class="toc" aria-label="On this page">${toc}</aside></div>` : `<main id="main" class="wide-page" tabindex="-1">${content}</main>`}<footer class="footer"><a class="brand" href="/">${logo}</a><span>A language for clear, predictable software.</span><a href="/changelog/">Changelog</a><a href="${site.github}/blob/main/LICENSE">MIT License ↗</a><span>Experimental · v${site.version}</span></footer><dialog id="search-dialog" aria-labelledby="search-label"><div class="search-top"><span aria-hidden="true">⌕</span><label id="search-label" class="sr-only" for="search-input">Search Skuld documentation</label><input id="search-input" type="search" placeholder="Search Skuld documentation…" autocomplete="off"><button class="close-dialog" aria-label="Close search">Esc</button></div><p id="search-status" class="search-status" role="status">Search guides, language features and library APIs.</p><div id="search-results"></div><div class="search-help"><span>↑ ↓ to navigate</span><span>Enter to open</span><span>Esc to close</span></div></dialog><div id="toast" role="status" class="sr-only"></div></body></html>`;
}
async function output(path: string, html: string) { const file = path === '/404/' ? 'dist/404.html' : `dist${path}index.html`; await mkdir(dirname(file), { recursive: true }); await writeFile(file, html); }
const card = (href: string, label: string, text: string, number: string) => `<a class="doc-card" href="${href}"><span class="card-number">${number}</span><span class="card-arrow">↗</span><h3>${label}</h3><p>${text}</p></a>`;
const cards = `<div class="cards">${card('/docs/getting-started/installation/', 'Getting started', 'Set up your toolchain. Write and run your first Skuld program.', '01')}${card('/docs/language/syntax/', 'Language guide', 'From your first binding to types, modules and error handling.', '02')}${card('/docs/standard-library/overview/', 'Standard library', 'Work with strings, files, JSON and network connections.', '03')}${card('/docs/tooling/cli/', 'Tooling', 'Check, build, format and test. Make the compiler part of your workflow.', '04')}</div>`;
const hello = 'func main() {\n    let name = "Skuld"\n    print("Hello, ${name}!")\n}';
await mkdir('dist/assets', { recursive: true });
await cp('public', 'dist', { recursive: true });
await cp('node_modules/@fontsource-variable/dm-sans/files/dm-sans-latin-wght-normal.woff2', 'dist/assets/dm-sans.woff2');
await cp('node_modules/@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-400-normal.woff2', 'dist/assets/ibm-plex-mono.woff2');
await cp('node_modules/@fontsource-variable/dm-sans/LICENSE', 'dist/assets/dm-sans-LICENSE.txt');
await cp('node_modules/@fontsource/ibm-plex-mono/LICENSE', 'dist/assets/ibm-plex-mono-LICENSE.txt');
await cp('src/site.css', 'dist/assets/site.css');
await writeFile('dist/assets/client.js', ts.transpile(await readFile('src/client.ts', 'utf8'), { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ES2022 }));
await output('/', shell('The Skuld language', 'An experimental statically typed native language for clear, predictable software.', '/', `<section class="home-hero"><div><p class="eyebrow">THE SKULD PROGRAMMING LANGUAGE</p><h1>Clear code.<br><span>Predictable behavior.</span></h1><p class="lead">A statically typed native language with readable syntax, explicit behavior, and tools that work together.</p><div class="actions"><a class="button primary" href="/docs/getting-started/installation/">Get started <span>→</span></a><a class="button" href="/docs/">Read the docs</a></div><p class="small muted">v${site.version} <span class="tiny-dot"></span> Experimental, by design</p></div><div class="hero-code">${codeBlock(hello, 'skuld main.skuld numbers')}<div class="terminal"><span>$</span> skuld run main.skuld<br><span class="output">Hello, Skuld!</span></div><div class="code-caption"><span>Native execution</span><span>Skuld → C → clang</span></div></div></section><section class="principles"><div><span class="eyebrow">01 / READABLE</span><h2>Simple where it matters.</h2><p>Local type inference and explicit function signatures. Read the code to understand the contract.</p></div><div><span class="eyebrow">02 / PREDICTABLE</span><h2>Make behavior visible.</h2><p>Checked arithmetic, value and reference types, and errors represented as values.</p></div><div><span class="eyebrow">03 / PRACTICAL</span><h2>A focused toolchain.</h2><p>Build native programs, format your source, run tests and navigate code with the language server.</p></div></section><section class="explore"><div class="section-heading"><div><p class="eyebrow">START EXPLORING</p><h2>A guide for every next step.</h2></div><a href="/docs/">Browse documentation →</a></div>${cards}</section>`));
await output('/docs/', shell('Documentation', 'Install Skuld, learn the language and explore the native toolchain.', '/docs/', `<p class="eyebrow">THE SKULD HANDBOOK <span class="status">v${site.version}</span></p><h1>Skuld documentation</h1><p class="lead">From your first program to the details that matter.<br>Learn the language, explore the library, and build with confidence.</p><div class="actions"><a class="button primary" href="/docs/getting-started/installation/">Get started →</a><a class="button" href="/docs/language/syntax/">Language reference</a></div>${cards}<section class="quick-start"><div class="section-heading"><h2 id="a-small-first-step">A small first step</h2><a href="/docs/getting-started/hello-world/">Full walkthrough →</a></div>${codeBlock(hello, 'skuld main.skuld numbers')}${codeBlock('skuld run main.skuld', 'bash')}<p class="muted">A compiler, a source file, and a native program. No project manifest required.</p></section><aside class="callout note"><strong>A living language</strong><p>Skuld is experimental. This handbook distinguishes implemented behavior from planned features. <a href="/docs/getting-started/introduction/#current-status">Read about the current status →</a></p></aside>`, `<p>START HERE</p><a href="/docs/getting-started/introduction/">What is Skuld?</a><a href="/docs/getting-started/installation/">Install the toolchain</a><a href="/docs/getting-started/hello-world/">Your first program</a><div class="toc-help"><span>Learning by doing?</span><a href="/examples/">Explore examples ↗</a></div>`, true));
const search = [];
for (let i = 0; i < pages.length; i++) {
  const page = pages[i]; const { html, headings } = render(page.body);
  const previous = pages[i - 1], next = pages[i + 1];
  const content = `<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/docs/">Docs</a><span>/</span><span>${escape(page.group)}</span><span>/</span><span>${escape(page.title)}</span></nav><div class="article-title"><h1>${escape(page.title)}</h1><span class="status ${page.status.toLowerCase()}">${escape(page.status)}</span></div><p class="lead">${escape(page.description)}</p><div class="prose">${html}</div><div class="article-source"><span>Current source · v${site.version}</span><a href="${site.github}/issues/new?title=${encodeURIComponent(`Documentation: ${page.title}`)}">Suggest an edit ↗</a></div><nav class="pagination" aria-label="Previous and next pages">${previous ? `<a href="${previous.path}"><span>← Previous</span><strong>${escape(previous.title)}</strong></a>` : '<span></span>'}${next ? `<a href="${next.path}"><span>Next →</span><strong>${escape(next.title)}</strong></a>` : ''}</nav>`;
  await output(page.path, shell(page.title, page.description, page.path, content, `<p>ON THIS PAGE</p>${headings.filter(h => h.level <= 3).map(h => `<a class="toc-link level-${h.level}" href="#${h.id}">${escape(h.title)}</a>`).join('')}<div class="toc-help"><span>Something unclear?</span><a href="${site.github}/issues">Discuss on GitHub ↗</a></div>`, true));
  search.push({ title: page.title, group: page.group, path: page.path, description: page.description, text: page.body.replace(/[#*`<>]/g, ''), headings });
}
for (const name of ['examples', 'changelog', 'playground']) {
  try { const raw = await readFile(`content/${name}.md`, 'utf8'); const { html } = render(raw); const title = name[0].toUpperCase() + name.slice(1); await output(`/${name}/`, shell(title, `${title} for the Skuld programming language.`, `/${name}/`, `<div class="standalone prose">${html}</div>`)); } catch (error) { if (process.env.INITIAL_PREVIEW !== '1') throw error; }
}
await output('/404/', shell('Page not found', 'Find your way back to the Skuld documentation.', '/404/', `<section class="not-found"><p class="eyebrow">404 / PAGE NOT FOUND</p><h1>This page isn’t here.</h1><p class="lead">It may have moved, or the address may be incorrect.</p><div class="actions"><button class="button primary" data-search>Search documentation</button><a class="button" href="/docs/">Go to docs →</a></div></section>`));
await writeFile('dist/search-index.json', JSON.stringify(search));
await writeFile('dist/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/', '/docs/', '/examples/', '/playground/', '/changelog/', ...pages.map(p => p.path)].map(p => `<url><loc>${site.origin}${p}</loc></url>`).join('')}</urlset>`);
await writeFile('dist/robots.txt', `User-agent: *\nAllow: /\nSitemap: ${site.origin}/sitemap.xml\n`);
console.log(`Built ${pages.length + 6} static pages. No hydration or client framework.`);
