use crate::span::Span;

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    Function,
    Let,
    Var,
    Return,
    If,
    Else,
    While,
    Loop,
    Break,
    Continue,
    New,
    Weak,
    Class,
    Struct,
    Impl,
    Interface,
    Enum,
    Match,
    Import,
    Const,
    Pub,
    For,
    In,
    Static,
    Extern,
    Unsafe,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Comma,
    Dot,
    DotDot,
    DotDotEqual,
    Colon,
    Arrow,
    FatArrow,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Equal,
    EqualEqual,
    BangEqual,
    Less,
    Greater,
    LessEqual,
    GreaterEqual,
    Bang,
    Question,
    AndAnd,
    OrOr,
    Ampersand,
    Pipe,
    Caret,
    Tilde,
    LessLess,
    GreaterGreater,
    PlusEqual,
    MinusEqual,
    StarEqual,
    SlashEqual,
    AmpersandEqual,
    PipeEqual,
    CaretEqual,
    LessLessEqual,
    GreaterGreaterEqual,
    Identifier(String),
    Integer(u64),
    Float(f64),
    String(String),
    /// Text before the first `${` of an interpolated string.
    InterpolationBegin(String),
    /// Text between one `}` and the next `${`.
    InterpolationPart(String),
    /// Text after the last `}`, up to the closing quote.
    InterpolationEnd(String),
    Char(char),
    Boolean(bool),
    Eof,
}
